version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: birthday_notificator_db
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5442:5432"
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db: