GET /api/v1/user HTTP/1.1
Host: localhost:8080
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthbWlsXzZAdmsuY29tIiwiZXhwIjoxNzE5NTA2NzAzLCJpZCI6IjEyNWFjMDc1LWNiMGQtNDQ5Ny1iODk2LTA3MGFjMTcxZTNlMSJ9.d0LnMjsspbb9GJZN2I0BdAZ5TMD0I1qwJsqIHR8wjF0